---
title: "LDAQDA"
author: "Sophia Gan"
date: "2024-04-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(modelr)
library(broom)
library(ISLR)
library(ROCR)
library(MASS)
library(caret)
library(ggplot2)
library(klaR)
library(dplyr)
```


```{r}
data <- read_csv("train_data.csv")
reduced_data <- data[c("Area", "MinorAxisLength", "ShapeFactor2", "ShapeFactor3", "Y")]
scaled_reduced_data <- scale(reduced_data[c("Area", "MinorAxisLength", "ShapeFactor2", "ShapeFactor3")])
scaled_reduced_data <- as.data.frame(scaled_reduced_data)
scaled_reduced_data["Y"] <- data$Y

# Assuming 'Y' is the target variable and it's a factor
data$Y <- as.factor(data$Y)

# Prepare training control
train_control <- trainControl(method = "cv", number = 5)  # 5-fold cross-validation

# LDA Model
set.seed(123)
lda_model <- train(Y ~ ., data = data, method = "lda", trControl = train_control)
print(lda_model)

# QDA Model
set.seed(123)
qda_model <- train(Y ~ ., data = data, method = "qda", trControl = train_control)
print(qda_model)

```

lda on whole data
```{r}
set.seed(123)
ind <- sample(2, nrow(data),
              replace = TRUE,
              prob = c(0.8, 0.2))
training <- data[ind==1,]
testing <- data[ind==2,]
```

```{r}
linear <- lda(Y~., training)
linear
```

```{r}
p <- predict(linear, training)
ldahist(data = p$x[,1], g = training$Y)
```

classification rate
```{r}
p1 <- predict(linear, training)$class
tab <- table(Predicted = p1, Actual = training$Y)
tab
```

```{r}
sum(diag(tab))/sum(tab)
```

seperation graph
```{r}
pca <- prcomp(training[, -which(names(training) == "Y")], scale. = TRUE)
pca_data <- data.frame(Y = training$Y, PC1 = pca$x[,1], PC2 = pca$x[,2])
```

```{r}
ggplot(pca_data, aes(x = PC1, y = PC2, color = Y)) +
    geom_point() +
    scale_y_continuous(limits = c(-10, 10)) +
    theme_minimal()
```

lda on reduced data
```{r}
set.seed(123)
ind_sca <- sample(2, nrow(scaled_reduced_data),
              replace = TRUE,
              prob = c(0.8, 0.2))
training_scale <- scaled_reduced_data[ind_sca==1,]
testing_sclae <- scaled_reduced_data[ind_sca==2,]
```

```{r}
linear_scale <- lda(Y~., training_scale)
linear_scale
```

```{r}
p_scale <- predict(linear_scale, training_scale)
ldahist(data = p_scale$x[,1], g = training_scale$Y)
```

```{r}
p1_scale <- predict(linear_scale, training_scale)$class
tab_scale <- table(Predicted = p1_scale, Actual = training_scale$Y)
tab_scale
```

```{r}
sum(diag(tab_scale))/sum(tab_scale)
```


